name: image-clusterduck
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - dbus=1.13.12
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2020.0
  - joblib=0.14.1
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pcre=8.43
  - pip=20.0.2
  - pyopengl=3.1.1a1
  - pyqt=5.9.2
  - pyqtgraph=0.10.0
  - python=3.6.13
  - qt=5.9.7
  - readline=7.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=45.2.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - fdict==0.8.1
    - mss==5.0.0
    - opencv-python==4.2.0.32
    - pebble==4.5.0
